[package]
name = "bene-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-alpha", features = [] }

[dependencies]
tauri = { version = "=2.0.0-alpha.18", features = [] }
tauri-runtime-wry = "=1.0.0-alpha.6" # hack to make tauri RC compile. remove when possible
serde = { workspace = true }
serde_json = "1.0"
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
tokio = { workspace = true, features = ["full"] }
bene-epub = { path = "../bene-epub" }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
specta = { workspace = true }
tauri-specta = { git = "https://github.com/oscartbeaumont/tauri-specta", branch = "tauri2-alpha18", features = ["javascript", "typescript"] }
quick-xml = { workspace = true }
reqwest = "0.11.23"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

